[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/","@chainlink/interfaces/=lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
